name: Test suite

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  load-test:
    runs-on: ubuntu-latest
    container: artilleryio/artillery:latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Make reports directory
      run: mkdir reports

    - name: Start the webservice
      run: docker-compose up -d

    - name: Wait for API
      uses: iFaxity/wait-on-action@v1.1.0
      with:
        resource: http://localhost:5000/locations

    - name: Execute load tests
      run: /home/node/artillery/bin/run run --output reports/report.json tests/demo_api_load.yml
      
    - name: Create html Report
      run: /home/node/artillery/bin/run report --output reports/report.html reports/report.json

    - name: Archive test report
      uses: actions/upload-artifact@v2
      with:
        name: artillery-test-report
        path: reports/*
